version: "3.3"

services:
  restore-cats-postgres:
    image: postgres:alpine
    volumes:
      - postgres-backup-restore-volume:/backup
    environment:
      PGUSER: demo
      PGPASSWORD: ${POSTGRES_PASSWORD:-hcFWQgb5gDJA4EWw8Sp7}
      PGHOST: db
      PGDATABASE: cats
    restart: "no"
    command: bash -c 'echo "*:*:*:*:$${PGPASSWORD}" > ~/.pgpass && chmod 0600 ~/.pgpass && pg_restore --verbose --no-owner --clean --if-exists --dbname=$${PGDATABASE} /backup/$${PGDATABASE}.sql.gz'

volumes:
  postgres-backup-restore-volume:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.178.35,rw
      device: ":/srv/nfs/postgres-backup-cats-swarm"

networks:
  default:
    external:
      name: cats_default
